<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <?php if($customerSession->isLoggedIn()):?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
            data-mage-init='{
                "Magento_Checkout/js/proceed-to-checkout":{
                    "checkoutUrl":"<?= $escaper->escapeJs($block->getCheckoutUrl()) ?>"
                }
            }'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()): ?>
                disabled="disabled"
            <?php endif; ?>>
        <span><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
    </button>
    <?php else:?>
        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="checkout" class="action primary" title="<?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>"><span><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span></a>
    <?php endif;?>
<?php endif?>
