<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<style>
    .mb-ajaxsuite-popup-wrapper .mb-login-popup-title {
    padding: 20px 25px !important;
}
</style>
<?php $_product = $block->getProduct(); ?>
<div class="ajaxwishlist-msg">
    <div class="mb-login-popup-title center">
        <strong><?= __('Please login'); ?></strong>
    </div>
    <div class="mb-ajaxsuite-popup-border ajaxwishlist-error-box">
        <p class="mb-message-error"><?= __('Please log in before adding product to your wishlist.'); ?></p>
        <div class="ajaxwishlist-buttons">
            <button type="button" id="ajaxwishlist_btn_close_popup" class="action primary mb-ajaxsuite-close"
                    title="<?= __('Close') ?>">
                <span><?= __('Close ') ?></span>
            </button>
            <button type="button" id="ajaxwishlist_btn_to_login" class="action focus primary"
                    title="<?= __('View Login') ?>">
                <span><?= __('Login') ?></span>
            </button>
        </div>
        <span class="spaceor">or </span>
        <div class="crtaccount"><a href="<?php echo $this->getUrl('customer/account/create');?>" class="createacount"><span style="color:#36656D;"><?= $block->escapeHtml(__('Create an Account')) ?></span></a></div>
    </div>
</div>
