<?php
/** @var \Sparsh\Brand\Block\BrandSlider $block */
$brandCollection = $block->getBrandCollection();

if (!empty($brandCollection)) {
    ?>
    <div>
        <div class="content-heading">
            <h2 class="title"><?= $block->escapeHtml(('Brands')); ?></h2>
        </div>
        <div class="sparsh-brand-slider">
            <?php foreach ($brandCollection as $brand) {
                $imageSize=getimagesize($brand['imageSize']);
                ?>       
                <div class="brand-title">
                    <a href="<?= $brand['brandUrl'] ?>">
                        <?php if ($imageSize[0]==210 && $imageSize[1]==50) { ?>
                        <img src="<?= $brand['brandImageUrl'] ?>" />
                        <?php } else { ?>
                        <img src="<?= $brand['resizeUrl'] ?>" />
                        <?php }  ?>
                    </a>
                    <b><?= $brand['title'] ?></b>
                </div>
            <?php } ?>
            </div>
        </div>
        <script>
            require([
                'jquery',
                'slick'
                ], function ($) {
                    jQuery(document).ready(function () {
                        $('.sparsh-brand-slider').slick({
                            infinite: false,
                            slidesToShow: 5,
                            slidesToScroll: 1,
                            dots: false,
                            autoplay: false,
                            arrows: true,
                            responsive: [
                            {
                                breakpoint: 9999,
                                settings: {
                                    slidesToShow: 5,
                                    slidesToScroll: 1,
                                }
                            },
                            {
                                breakpoint: 1024,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 3,
                                }
                            },
                            {
                                breakpoint: 600,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 2,
                                    variableWidth: false,
                                }
                            },
                            {
                                breakpoint: 480,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1,
                                    arrows: true,
                                    variableWidth: false,
                                }
                            }
                        ]
                    });
                    });
                });
            
            </script>
<?php } ?>
