<?php
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on')
    $url = "https://";
else
    $url = "http://";
$url .= $_SERVER['HTTP_HOST'];

$blogName = $block->getBlogName();
// dump($blogName);
// die();
?>
<style>
    .main-container {
        display: flex;
    }

    .main-left-container {
        width: 70%;
        padding: 20px;
        -ms-overflow-style: none;
        scrollbar-width: none;
    }

    .main-left-container::-webkit-scrollbar {
        display: none;
    }

    .main-right-container {
        width: 30%;
        padding: 20px;
    }

    .main-heading {
        text-align: center;
        width: fit-content;
        margin: 0px 20px;
        border-bottom: 1px solid blueviolet;
    }

    .main-heading:first-child {
        border-bottom: 1px solid orange;
    }

    .name-heading {
        font-size: 50px;
        margin-top: 20px;
        text-align: center;
    }

    h1 {
        font-weight: 400;
    }

    h2 {
        font-weight: 400;
    }

    .button-continue {
        display: block;
        width: fit-content;
        margin: auto;
        background-color: white;
        color: #EC521E;
        padding: 10px 30px;
        border: 1px solid #EC521E;
        border-radius: 25px;
        text-decoration: none;
        font-size: 15px;
    }

    .button-continue:visited,
    .button-continue:link {
        color: #EC521E;
    }

    a {
        text-decoration: none;
        color: unset;
    }

    a:visited,
    a:link {
        color: unset;
    }

    .button-continue:hover {
        background-color: #EC521E;
        color: white;
        transition: 1s;
    }

    .information-blog {
        list-style: none;
        display: flex;
        /* justify-content: space-around; */
        padding: 0;
        font-size: 11px;
        width: fit-content;
        margin: auto;
        flex-wrap: wrap;
        text-align: center;
        justify-content: center;
    }

    .information-blog li {
        width: fit-content;
        padding: 0px 10px;
    }

    .information-blog li span {
        margin-left: 5px;
    }

    .artical-main::first-letter {
        font-size: 36px;
        color: #EC521E;
    }

    .blog-artical {
        margin-top: 50px;
    }

    .blog-artical:first-child {
        margin-top: 0px;
    }

    .heading-flex {
        display: flex;
        align-items: center;
        width: fit-content;
        margin: auto;
    }

    .pageno {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
    }

    .pbtn {
        margin: 5px;
        border-radius: 25px;
        background-color: #eee;
        height: 50px;
        width: 50px;
        display: flex;
        justify-content: center;
        align-items: center;

    }

    @media screen and (max-width:992px) {
        .main-container {
            display: block;
        }

        .main-left-container {
            width: 100%;
            padding: 20px;
        }

        .main-right-container {
            width: 100%;
            padding: 20px;
        }
    }
</style>
<br><br>
<div class="main-container">
    <?php if (isset($blogName[0]) && $blogName[0] != 'page') { ?>
        <div class="main-left-container">
            <?php
            $blog = $block->getBlog($blogName[0]);
            foreach ($blog as $blg) {
                ?>
                <div class="blog-artical">
                    <div class="heading-flex">
                        <?php foreach ($blg->activities as $activity) { ?>
                            <div class="main-heading">
                                <?php echo $activity ?>
                            </div>
                        <?php } ?>
                    </div>
                    <h1 class="name-heading">
                        <?php echo $blg->title->rendered; ?>
                    </h1>
                    <br>
                    <ul class="information-blog">
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-calendar-heart" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5ZM1 14V4h14v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1Zm7-6.507c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
                            </svg><span>5 MONTHS AGO</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-alarm" viewBox="0 0 16 16">
                                <path
                                    d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z" />
                                <path
                                    d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z" />
                            </svg><span>READ TIME: 3 MINUTES</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                            </svg><span>BY OUTDOORGOATS (OUTDOORGOATS)</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-chat-right-heart" viewBox="0 0 16 16">
                                <path
                                    d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2Zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12Z" />
                                <path d="M8 3.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
                            </svg><span>LEAVE A COMMENT</span></li>
                    </ul>
                    <br>
                    <?php $blog_image_url = !empty($each->acf->cover_image) ? $each->acf->cover_image : "https://wcimages-prod.s3.ap-south-1.amazonaws.com/blogimages/dbad50f3-d0bb-4ed6-b494-a1e935a828ac/BlogCover"; ?>
                    <img src="<?php echo $blog_image_url ?>" alt="" width="100%">
                    <br>
                    <br>
                    <p class="artical-main">
                        <?php
                        echo $blg->post_content;
                        ?>
                    </p>
                </div>
            <?php } ?>
        </div>
        <?php
    } else {
        ?>
        <div class="main-left-container">
            <?php
            if (isset($blogName) && $blogName[0] == 'page') {
                $pg = $blogName[1];
            } else {
                $pg = 1;
            }
            $blogs = $block->getBlogs($pg);
            foreach ($blogs as $key => $blog) {
                ?>
                <div class="blog-artical">
                    <div class="heading-flex">
                        <?php foreach ($blog->activities as $activity) { ?>
                            <div class="main-heading">
                                <?php echo $activity ?>
                            </div>
                        <?php } ?>
                    </div>
                    <h1 class="name-heading">
                        <?php echo $blog->title->rendered; ?>
                    </h1>
                    <br>
                    <ul class="information-blog">
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-calendar-heart" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5ZM1 14V4h14v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1Zm7-6.507c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
                            </svg><span>5 MONTHS AGO</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-alarm" viewBox="0 0 16 16">
                                <path
                                    d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z" />
                                <path
                                    d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z" />
                            </svg><span>READ TIME: 3 MINUTES</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                            </svg><span>BY OUTDOORGOATS (OUTDOORGOATS)</span></li>
                        <li><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" fill="currentColor"
                                class="bi bi-chat-right-heart" viewBox="0 0 16 16">
                                <path
                                    d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2Zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12Z" />
                                <path d="M8 3.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
                            </svg><span>LEAVE A COMMENT</span></li>
                    </ul>
                    <br>
                    <img src="<?php echo $blog->acf->cover_image; ?>" alt="" width="100%">
                    <br>
                    <br>
                    <p class="artical-main">
                        <?php
                        $content = $blog->post_content;
                        $content = substr($content, 0, 500);
                        $content = substr($content, 0, strrpos($content, " "));
                        $content = $content . " ...";
                        echo $content;
                        ?>
                    </p>
                    <a href="<?php echo $url ?>/blog/<?php echo $blog->slug ?>" class="button-continue">Continue Reading</a>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="main-right-container">
        <div class="inner-right-content">
            <h2>Recent Posts</h2>
            <a href="#">Best cycles in 2023
                Alchi -The Apricot hamlet in Ladakh
                Anti-Packing list for backpackers. A guide to lightweight Backpacking
                Merak- An unexplored village in ladakh
                Manali to Leh pt 2</a>
            <br>
            <br>
            <h2>Recent Comments</h2>
            <a href="#">No comments to show.</a>
        </div>
    </div>
</div>
<div class="pagination">
    <?php if (isset($blogName) && $blogName[0] == 'page' || !isset($blogName[0])) { ?>
    <div class="pageno">
        <?php if (!isset($blogName) || $blogName[0] != 'post') { ?>
            <a href="<?php echo $url ?>/blog/page/1" class="pbtn endval">1</a>
        <?php } ?>
        <?php
        $total_pages = 12;
        if (isset($blogName) && $blogName[0] == 'page') {
            if ($blogName[1] < 4) {
                for ($i = 2; $i <= 4; $i++) { ?>
                    <a href="<?php echo $url ?>/blog/page/<?php echo $i ?>" class="pbtn"><?php echo $i; ?></a>
                <?php } ?> >>
                <?php
            } else if ($blogName[1] > $total_pages - 3) {
                ?> << <?php
                 for ($i = $total_pages - 3; $i <= $total_pages - 1; $i++) { ?> <a
                                href="<?php echo $url ?>/blog/page/<?php echo $i ?>" class="pbtn"><?php echo $i; ?></a>
                    <?php }
            } else {

                ?>
                        << <a href="<?php echo $url ?>/blog/page/<?php echo $blogName[1] - 1 ?>" class="pbtn"><?php echo $blogName[1] - 1; ?></a>
                            <a href="<?php echo $url ?>/blog/page/<?php echo $blogName[1] ?>" class="pbtn"><?php echo $blogName[1]; ?></a>
                            <a href="<?php echo $url ?>/blog/page/<?php echo $blogName[1] + 1 ?>" class="pbtn"><?php echo $blogName[1] + 1; ?></a> >>

                    <?php }
        } else if (!isset($blogName) || $blogName[0] != 'post') {
            for ($i = 2; $i <= 4; $i++) { ?>
                            <a href="<?php echo $url ?>/blog/page/<?php echo $i ?>" class="pbtn"><?php echo $i; ?></a>
                    <?php } ?> >>
                    <?php
        } ?>
                <?php if (!isset($blogName) || $blogName[0] != 'post') { ?>
                    <a href="<?php echo $url ?>/blog/page/<?php echo $total_pages ?>" class="pbtn endval"><?php echo $total_pages; ?></a>
                <?php } ?>

    </div>
    <?php } ?>
</div>
<br><br>