<?php
/** @var \Sparsh\Brand\Block\BrandSlider $block */
$brandCollection = $block->getBrandCollection();
$brandCollection = json_decode($brandCollection, true);
// dd($brandCollection);
if (!empty($brandCollection)) {
    ?>

    <div class="sparsh-brand-slider owl-carousel">
        <?php foreach ($brandCollection['items'] as $brand) {
            // $imageSize=getimagesize($brand['imageSize']);
          if ($brand['username'] == 'cocod') {
              continue;
          }
            ?>       
            <div class="brand-title">
                <a href="athlete/<?= $brand['username'] ?>">
                    
                    <img src="<?= $brand['image_url'] ?>" />
                    
                </a>
                <b><?= $brand['title'] ?></b>
                <p><?= $brand['sport'] ?></p>
            </div>
        <?php } ?>
    </div>

    <script type="text/javascript">
      require([
        'jquery',
        'owl.carousel/owl.carousel.min'
      ], function ($) {
        $(".sparsh-brand-slider.owl-carousel").owlCarousel({
          autoplay: false,
          autoplayTimeout: 5000,
          autoplayHoverPause: true,
          loop: true,
          navRewind: true,
          lazyLoad:true,
          margin: 20,
          nav: false,
          dots: true,
          responsive: {
            0: {
              items:2
            },
            640: {
              items:2
            },
            768: {
              items:3
            },
            992: {
              items:4
            },
            1200: {
              items:4
            }
          }
        });
      });
    </script>
<?php } ?>
