<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_Xsearch
*/
?>
<?php
/**
 * @var \Amasty\Xsearch\Block\Search\Product $block
 * @var \Magento\Framework\Escaper $escaper
 * @var array $products
 * phpcs:ignoreFile
 */

$products = $block->getProducts();
?>
<?php if (count($products)): ?>
    <ul class="amsearch-product-list"
        data-mage-init='{
            "amsearchProductItemInit": {}
        }'>
        <?php foreach ($products as $id => $product): ?>
            <li class="amsearch-item product-item"
                data-click-url="<?= $escaper->escapeUrl($block->getFullLink($product['url'])) ?>">
                <a class="amsearch-image"
                   title="<?= $escaper->escapeHtmlAttr($block->stripTags($product['name'])); ?>"
                   href="<?= $escaper->escapeUrl($block->getFullLink($product['url'])) ?>">
                    <?= /* @noEscape */ $product['img'] ?>
                </a>
                <a class="amsearch-link product-item-link"
                   href="<?= $escaper->escapeUrl($block->getFullLink($product['url'])) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->stripTags($product['name'])); ?>">
                    <?= /* @noEscape */ $product['name'] ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
