<?php
/**
 * @var \Amasty\ElasticSearch\Block\Adminhtml\System\Config\ConnectionChecker $block
 */
?>
<button class="scalable"
        type="button"
        id="<?= $block->getHtmlId() ?>"
        data-mage-init='{"Amasty_ElasticSearch/js/connectionchecker":<?= /* @noEscape */ $block->getJsonConfig();?>}'>
    <span id="<?= $block->getHtmlId() ?>_result">
        <?= $block->escapeHtml($block->getButtonLabel()) ?>
    </span>
</button>
