<?php
/** @var $block \Wishtech\ProductZoom\Block\Zoom */
?>
<script type="text/javascript">
    require([
        'jquery',
        'wishtech/elevatezoom',
        ], function($){
            "use strict";
            if( $(window).width() < 768 ) return;

            var options = <?php echo $block->getJsonConfig() ?>;
            $('head').append('<style type="text/css">.zoomContainer{z-index:' + options.zIndex + '}</style>');
            $(document).on('fotorama:load fotorama:showend fotorama:fullscreenenter fotorama:fullscreenexit', function (event, fotorama, extra) {
                $('.zoomContainer').remove();
                if(event.type == 'fotorama:fullscreenenter') return;
                if( fotorama.activeFrame.type != 'image' || $('body').hasClass('fotorama__fullscreen') ) return;
                var img = $('.product.media .fotorama__stage .fotorama__active .fotorama__img');
                if(!img.length) return;
                var defaults = {
                    zoomWindowWidth : img.width(),
                    zoomWindowHeight: img.height()
                };
                var settings = $.extend(defaults, options);
                if(fotorama.activeFrame.full) img.data('zoom-image', fotorama.activeFrame.full);
                img.elevateZoom(settings);
            });
    });
</script>
<?php if($block->isZoomTypeWindow()) { ?>
<style>
.zoomLens{width:50px !important;height:50px !important;border-radius: 0px !important;}
</style>
<?php } ?>
