<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php if ($block->isCustomerLoggedIn()) :?>
    
    <div id="mb-ajaxlogin-wrapper">
        <?= $block->getChildHtml('ajaxlogin.popup.message'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.forgot'); ?>
    </div>
<?php else:?>
    
    <div id="mb-ajaxlogin-wrapper">
        <div class="mb-login-popup">
            <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-login">
                <div class="login-container">
                    <ul class="tabs-menu customer-tabs-menu">
                        <li>    
                            <a href="javascript:void(0);" data-tab="timber-login" class="login-title current">
                                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign in')) ?></strong>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" data-tab="timber-register" class="login-title">
                                <strong id="block-customer-register-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign Up')) ?></strong>
                            </a>
                        </li>
                    </ul>




               <?php
                    $blockObj= $block->getLayout()->createBlock('Mageplaza\SocialLogin\Block\Popup\Social');
                    //echo $blockObj->getMyCustomMethod();
                    $availableSocials = $blockObj->getAvailableSocials();
                    $childBlock = $blockObj->getChildBlock('request.info');

                ?>
                <ul class="tabs-menu-social">
                    <li>
                <div class="block social-login-authentication-channel account-social-login">
                    <div class="block-content login-social noramal-login">
                        <?php foreach ($availableSocials as $key => $social): ?>
                        <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $social['label'] ?>-login">
                            <a class="btn btn-block btn-social btn-<?= strtolower($social['label']) ?>"
                                data-mage-init='{"socialProvider": {"url": "<?= $social['login_url'] ?>", "label": "<?= __('Login By %1', $social['label']) ?>"}}'>
                                <span class="fa fa-<?= strtolower($social['label']) ?>"></span>
                                <?= __('Sign in with %1', $social['label']) ?>
                            </a>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="block-content login-social wishlist-login" style="display:none">
                        <?php foreach ($blockObj->getSocialWishlistButtonsConfig() as $key => $social): ?>
                        <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $social['label'] ?>-login">
                            <a class="btn btn-block btn-social btn-<?= strtolower($social['label']) ?>"
                                data-mage-init='{"socialProvider": {"url": "<?= $social['url'] ?>", "label": "<?= __('Login By %1', $social['label']) ?>"}}'>
                                <span class="fa fa-<?= strtolower($social['label']) ?>"></span>
                                <?= __('Sign in with %1', $social['label']) ?>
                            </a>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="block-content login-social checkout-login" style="display:none">
                        <?php foreach ($blockObj->getSocialButtonsConfig() as $key => $social): ?>
                        <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $social['label'] ?>-login">
                            <a class="btn btn-block btn-social btn-<?= strtolower($social['label']) ?>"
                                data-mage-init='{"socialProvider": {"url": "<?= $social['url'] ?>", "label": "<?= __('Login By %1', $social['label']) ?>"}}'>
                                <span class="fa fa-<?= strtolower($social['label']) ?>"></span>
                                <?= __('Sign in with %1', $social['label']) ?>
                            </a>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
                </li>

                <li>
                    
                    <div class="block social-login-authentication-channel account-social-login">
                    <div class="block-content">
                     <div class="actions-toolbar social-btn social-btn-actions-toolbar Google-login">
                     <a class="btn btn-block btn-social btn-google">
                     <span class="fa fa-apple"></span>
                       Continue with Apple 
                     </a>
                     </div>
                     </div>
                    </div>
                     
                </li>

                </ul>



                <style type="text/css">
                    .request-popup {
                        overflow-y: unset;
                        max-width: 800px;
                        left: 30%;
                    }

                    .request-popup .modal-header {
                        padding: 0;
                    }

                    .request-popup .modal-header button.action-close {
                        color: white;
                        z-index: 100;
                    }

                    .request-popup .modal-content {
                        padding: 0;
                    }
                    ::placeholder {
  color: #ccc;
  opacity: 1; /* Firefox */
}

:-ms-input-placeholder { /* Internet Explorer 10-11 */
 color: #ccc;
}

::-ms-input-placeholder { /* Microsoft Edge */
 color: #ccc;
}
                </style>
                
                <div class="spaor rigsterpoup"><span>or</span></div>

                    
                    <div class="tab">
                        <div id="tab-1" class="timber-login tab-content current"> 
                            <?php echo $block->getChildHtml('ajaxlogin.popup.login'); ?>
                            
                        </div>
                        <div id="tab-2" class="timber-register tab-content" style="display: none;">
                            <?php echo $block->getChildHtml('ajaxlogin.popup.register'); ?>
                        </div>
                    </div>
                </div>
 

            </div>
        </div>
        <?= $block->getChildHtml('ajaxlogin.popup.forgot'); ?>
        <?= $block->getChildHtml('ajaxlogin.popup.message'); ?>
    </div>
  <?php endif;?>
  <script type="text/javascript">
    require(['jquery',"mage/url"],function($,url){
        $(document).ready(function() {
            $('ul.customer-tabs-menu li a').click(function(){
                $('.tab-content').hide();
                var tab_id = $(this).attr('data-tab');
                $('ul.tabs-menu li a').removeClass('current');
                $('.tab-content').removeClass('current');
                $(this).addClass('current');
                $("."+tab_id).addClass('current');
                $("."+tab_id).show();
            })
        });
    });
</script>
 
