<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$_product = $block->getProduct();
?>
<?php if ($block->isWishListAllowed()) : ?>
    <?php if($customerSession->isLoggedIn()):?>
        <a href="#"
        class="action towishlist"
        data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
        data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
    <?php else:?>
        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="wishlist" data-product="<?= $_product->getId()?>" class="action towishlist" ></a>
    <?php endif;?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>