<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();

$productArray = iterator_to_array($_productCollection);

if(!isset($_GET['product_list_order'])){
    shuffle($productArray);
}

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$customHelper = $this->helper('Gearup\Partner\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

// Daily deal Helper
$_dailydealhelper =$this->helper('Smartwave\Dailydeals\Helper\Data');

$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');

$_category_config = $_portohelper->getConfig('porto_settings/category');
$_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
$_product_label_config = $_portohelper->getConfig('porto_settings/product_label');
$_lazyload = $_portohelper->getConfig('porto_settings/optimization/lazyload');
$_inscroll = $_portohelper->getConfig('layered_navigation/general/infinite_scroller');
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $_objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');                   
?>
<?php $iterator = 1; ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $hover_image = 'category_page_grid-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $columns = 'columns'.$_category_grid_config['columns'];
        $product_type = $_category_grid_config['product_type'];
        if($product_type == null) {
            $product_type = 1;
        }
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $hover_image = 'category_page_list-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $columns = '';
        $product_type = 0;
    }
    $image_width = 265;
    $image_height = 295;
    $aspect_ratio = $_category_config['aspect_ratio'];
    if($aspect_ratio)
        $image_height = $image_width;
    ?>
    <div class="products wrapper <?php echo $viewMode; ?> <?php echo $columns; ?> products-<?php echo $viewMode; ?> <?php if($product_type == 2): ?>no-padding divider-line<?php endif; ?> <?php if($product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8): ?>no-padding<?php endif; ?> <?php if($product_type == 6): ?>divider-line<?php endif; ?>">
        <?php $iterator = 1; ?>
        <ol class="filterproducts products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($productArray as $_product): 
                //echo "<pre>"; print_r($_product->debug()); echo "</pre>";
                ?>
                <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info type<?php echo $product_type; ?>" data-container="product-grid">
                    <?php // Product Image ?>
                    <div class="product photo product-item-photo">
                        <a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1" target="_blank">
                        <?php
                            if($aspect_ratio)
                                $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productImage = $_imagehelper->init($_product, $image)->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize($image_width, $image_height);
                            $productImageUrl = $productImage->getUrl();
                        ?>
                            <img class="product-image-photo default_image <?php if(!$_lazyload): ?>porto-lazyload<?php endif;?>" <?php if(!$_lazyload): ?>data-<?php endif; ?>src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php //echo $productImage->getLabel();?>"/>
                        <?php if($_category_config['alternative_image']): ?>
                        <?php
                            if($aspect_ratio)
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize($image_width, $image_height);
                            $productHoverImageUrl = $productHoverImage->getUrl();
                        ?>
                            <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                            <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php //echo $productHoverImage->getLabel();?>"/>
                            <?php endif; ?>
                        <?php endif; ?>
                        </a>

                        <?php
                        $recommendedBy = $customHelper->getBrandName($_product->getId());
                        if ($recommendedBy) { ?>
                            <div class="recommended-athelete-section">
                                <p><span>Recommended by </span><label><a href="<?= $this->getUrl().$recommendedBy['brandUrlKey']; ?>" target="_blank"><?= $recommendedBy['brandName']; ?></a></label>
                                    <span class="recommendedBy-tick"><img src="<?php echo $mediaUrl;?>wysiwyg/Vector.png" /></span>
                                </p>
                            </div>
                        <?php } ?>
                        
                        <?php if($product_type == 3 || $product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8 || $product_type == 9): ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable() || $_product->getTypeId() == "configurable"): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <!-- Dailydeal Product data -->
                        <?php if($_dailydealhelper->isDealProduct($_product->getId())) : ?>
                        <?php $unique_id = rtrim(base64_encode(md5(microtime())),"="); ?>
                        <input type="hidden" id="todate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealToDate($_product->getSku()); ?>" >
                        <input type="hidden" id="fromdate_<?php echo $unique_id; ?>" value="<?php echo $_dailydealhelper->getDailydealFromDate($_product->getSku()); ?>">
                        <div class="sw-dailydeal-wrapper" style="display:none;" data-unique-id="<?php echo $unique_id; ?>">
                            <div class="sw-dailydeal">
                                <p id="expired_<?php echo $unique_id; ?>"></p>
                                <div class="countdowncontainer countdowncontainer_<?php echo $unique_id; ?>" style="display:none;">
                                    <span class="dailydeal-label">
                                        <?php echo __('Ends In:'); ?>
                                    </span>
                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number day"><p id="countdown_days_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption"><?php echo __('Day(s), '); ?></div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number hour"><p id="countdown_hours_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption">:</div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number min"><p id="countdown_minutes_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption">:</div>
                                    </span>

                                    <span class="number-wrapper">
                                        <div class="line"></div>
                                        <span class="number sec"><p id="countdown_seconds_<?php echo $unique_id; ?>">00</p></span>
                                        <div class="caption"></div>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <!-- Dailydeal Product End -->
                    </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <div class="combined-name-wishlist-section">

                            <strong class="product-brand-name">
                                <a class="product-item-link"
                                   href="<?php echo $_product->getProductUrl() ?>" target="_blank">
                                    <?php echo $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?>
                                </a>
                            </strong>
                              <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <?php if($customerSession->isLoggedIn()):?>
                                        <a href="#"
                                            class="action towishlist actions-secondary"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            
                                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                        </a>
                                    <?php else:?>
                                        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="wishlist" data-product="<?= $_product->getId()?>" class="action towishlist actions-secondary" ></a>
                                    <?php endif;?>
                                    
                                <?php endif; ?>
                            
                        </div>

                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo $_product->getProductUrl() ?>" target="_blank">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>

                        <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                   class="action more" target="_blank">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </a>
                            </div>
                        <?php endif; ?>

                        <?php if($_category_config['rating_star']): ?>
                        <?php
                            $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                        ?>
                        <?php if($review_html): ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php else: ?>
                        <div class="product-reviews-summary short">
                            <div class="rating-summary">
                                <span class="label"><span>Rating:</span></span>
                                <div class="rating-result" title="0%">
                                    <span style="width:0"><span>0%</span></span>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>

                        <?php $simpleProduct = $_objectManager->create('Magento\Catalog\Model\ProductFactory')->create()->load($_product->getId());
                        $visibility = $simpleProduct->getVisibility();
                        if ($visibility == 1) {
                            $parent = $_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($_product->getId());
                            $productId = $parent[0];
                        } else {
                            $productId = $_product->getId();
                        }

                        ?>

                        <?php if($_category_config['product_price']): ?>
                            <?php if ($_product->getTypeId() == "configurable"):?>
                                <?php $productData = $_objectManager->create('Magento\Catalog\Model\ProductFactory')->create()->load($_product->getEntityId()); 
                                $basePrice = $_product->getPriceInfo()->getPrice('regular_price');
                                $regularPrice = $basePrice->getMinRegularAmount()->getValue();
                                $specialPrice = $_product->getFinalPrice();
                                if($specialPrice) :
                                ?>
                                     <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $productId;?>" data-price-box="product-id-<?php echo $productId;?>">
                                       
                                        <span class="special-price">
                                            <span class="price-container price-final_price tax weee">
                                                <span id="product-price-<?php echo $productId;?>" data-price-amount="<?php echo $specialPrice;?>" data-price-type="finalPrice" class="price-wrapper ">
                                                    <span class="price"><?php echo $priceHelper->currency($specialPrice, true, false);?></span>
                                                </span>
                                            </span>
                                        </span>
                                        <?php if($specialPrice != $regularPrice){ ?>
                                         <span class="old-price">
                                            <span class="price-container price-final_price tax weee">
                                                <span id="old-price-<?php echo $productId;?>" data-price-amount="<?php echo $regularPrice;?>" data-price-type="oldPrice" class="price-wrapper ">
                                                    <span class="price"><?php echo $priceHelper->currency($regularPrice, true, false);?></span>
                                                </span>
                                            </span>
                                        </span>
                                    <?php } ?>
                                    </div>

                                    <?php
                                    $product_label = "";
                                    if($_product_label_config['sale_label']) {
                                        $orgprice = $regularPrice;
                                        $specialprice = $specialPrice;
                                        $specialfromdate = $productData->getSpecialFromDate();
                                        $specialtodate = $productData->getSpecialToDate();
                                        $today = time();
                                        if(!$specialprice)
                                            $specialprice = $orgprice;
                                        if($specialprice < $orgprice) {
                                            if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                                if($_product_label_config['sale_label_percent']) {
                                                    $save_percent = 100-round(($specialprice/$orgprice)*100);
                                                    $product_label .= '<div class="product-label sale-label">('.$save_percent.'%'.' Off)</div>';
                                                } else {
                                                    $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                                }
                                            }
                                        }
                                    } 

                                    if($product_label)
                                        echo '<div class="product-labels">'.$product_label.'</div>';
                                    ?>
                                <?php else: ?>
                                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $productId;?>" data-price-box="product-id-<?php echo $productId;?>">
                                        <span class="normal-price">
                                            <span class="price-container price-final_price tax weee">
                                                <span id="normal-price-<?php echo $productId;?>" data-price-amount="<?php echo $_product->getMinimalPrice();?>" data-price-type="normalPrice" class="price-wrapper ">
                                                    <span class="price"><?php echo $priceHelper->currency($_product->getMinimalPrice(), true, false);?></span>
                                                </span>
                                            </span>
                                        </span>
                                    </div>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php echo $block->getProductPrice($_product) ?>
                            <?php endif; ?>
                            
                        <?php endif; ?>

                        <?php
                            $product_label = "";
                            /*if($_product_label_config['sale_label']) {
                                $orgprice = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $specialfromdate = $_product->getSpecialFromDate();
                                $specialtodate = $_product->getSpecialToDate();
                                $today = time();
                                if(!$specialprice)
                                    $specialprice = $orgprice;
                                if($specialprice < $orgprice) {
                                    if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                        if($_product_label_config['sale_label_percent']) {
                                            $save_percent = 100-round(($specialprice/$orgprice)*100);
                                            $product_label .= '<div class="product-label sale-label">('.$save_percent.'%'.' Off)</div>';
                                        } else {
                                            $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                        }
                                    }
                                }
                            }*/
                            if($_product_label_config['new_label']) {
                                $now = date("Y-m-d");
                                $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                $newsTo=  substr($_product->getData('news_to_date'),0,10);

                                if ($newsTo != '' || $newsFrom != ''){
                                    if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                        $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
                                    }
                                }
                            }
                            if($product_label)
                                echo '<div class="product-labels">'.$product_label.'</div>';
                        ?>

                        <?php //echo $block->getProductDetailsHtml($_product); ?>

                        <?php if($product_type != 3 && $product_type != 5 && $product_type != 6 && $product_type != 7 && $product_type != 8 && $product_type != 9): ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <?php if ($block->getMode() == 'grid'): ?>
                                <?php if($_category_config['addtowishlist'] && $product_type != 4): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <?php if($customerSession->isLoggedIn()):?>
                                        <a href="#"
                                            class="action towishlist actions-secondary"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            
                                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                        </a>
                                    <?php else:?>
                                        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="wishlist" data-product="<?= $_product->getId()?>" class="action towishlist actions-secondary" ></a>
                                    <?php endif;?>
                                    
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable() || $_product->getTypeId() == "configurable"): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php if($product_type == 10):?>
                                                <div class="qty-box">
                                                    <a href="javascript:void(0)" class="qtyminus"><i class="porto-icon-minus"></i></a>
                                                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                    <a href="javascript:void(0)" class="qtyplus"><i class="porto-icon-plus"></i></a>
                                                </div>
                                            <?php endif;?>
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <a href="<?php echo $_product->getProductUrl() ?>" target="_blank">
                                            <button type="button"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action primary">
                                                <span><?php echo __('More Details') ?></span>
                                            </button></a>
                                        </form>
                                        <?php /*echo $this->getLayout()
                                            ->createBlock('Mageprince\BuyNow\Block\Product\ListProduct')
                                            ->setProduct($_product)
                                            ->setTemplate('Mageprince_BuyNow::buynow-list.phtml')
                                            ->toHtml();*/
                                            ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($block->getMode() == 'grid'): ?>
                                <?php if($_category_config['addtowishlist'] && $product_type == 4): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <?php if($customerSession->isLoggedIn()):?>
                                        <a href="#"
                                            class="action towishlist actions-secondary"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            
                                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                        </a>
                                    <?php else:?>
                                        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="wishlist" data-product="<?= $_product->getId()?>" class="action towishlist actions-secondary" ></a>
                                    <?php endif;?>
                                    
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($block->getMode() == 'list'): ?>
                                <?php if($_category_config['addtowishlist']): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <?php if($customerSession->isLoggedIn()):?>
                                        <a href="#"
                                            class="action towishlist actions-secondary"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            
                                            data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                        </a>
                                    <?php else:?>
                                        <a href="<?= $this->getUrl('customer/account/login');?>" data-redirect="wishlist" data-product="<?= $_product->getId()?>" class="action towishlist actions-secondary" ></a>
                                    <?php endif;?>
                                    
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php echo($iterator == count($productArray)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if(isset($_inscroll) && $_inscroll):?>
    <div class="infinite-loader"><a href="javascript:void(0)" class="loading" style="display: none;"><?php echo __("Loading ..."); ?></a><a href="javascript:void(0)" class="btn-load-more"><?php echo __("Load More ..."); ?></a></div>
    <?php endif;?>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
                $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
                $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
                $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
                $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
                $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
                $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
                $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
                $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
                $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
                $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
                $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
                $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
                $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
      var app = {
          isAppleDevice: function() {
            if (navigator.userAgent.match(/(iPhone|iPod|iPad|Safari)/) != null) {
              return true;
            }
            return false;
          }
      }
    // Timer for LEFT time for Dailydeal product
        var _second = 1000;
        var _minute = _second * 60;
        var _hour = _minute * 60;
        var _day = _hour * 24;
        var timer;

        //Set date as magentodatetime
        var date = new Date('<?php echo $_dailydealhelper->getcurrentDate() ?>');
        if (app.isAppleDevice()) {
          var mdate = '<?php echo $_dailydealhelper->getcurrentDate() ?>';
          var dateParts = mdate.substring(0,10).split('-');
          var timePart = mdate.substr(11);
          date = dateParts[1] + '/' + dateParts[2] + '/' + dateParts[0] + ' ' + timePart;
          date = new Date(date);
        }
        var l_date = new Date();
        var offset_date = l_date - date;

        function showRemaining()
        {
            $(".sw-dailydeal-wrapper").each(function(){
                var unique_id = $(this).attr("data-unique-id");
                // get Value of dailydeal product
                var cid='countdown_'+unique_id;
                var daysid='countdown_days_'+unique_id;
                var hoursid='countdown_hours_'+unique_id;
                var minutesid='countdown_minutes_'+unique_id;
                var secondsid='countdown_seconds_'+unique_id;

                var startdateid='fromdate_'+unique_id;
                var id='todate_'+unique_id;

                var enddate = new Date($('#'+id).val());
                var dealstartdate=new Date($('#'+startdateid).val());
                if (app.isAppleDevice() && $('#'+id).val() && $('#'+startdateid).val()) {
                  var ledate = $('#'+id).val();
                  var ledateParts = ledate.substring(0,10).split('-');
                  var letimePart = ledate.substr(11);
                  enddate = ledateParts[1] + '/' + ledateParts[2] + '/' + ledateParts[0] + ' ' + letimePart;
                  enddate = new Date(enddate).getTime();

                  var lsdate = $('#'+startdateid).val();
                  var lsdateParts = lsdate.substring(0,10).split('-');
                  var lstimePart = lsdate.substr(11);
                  dealstartdate = lsdateParts[1] + '/' + lsdateParts[2] + '/' + lsdateParts[0] + ' ' + lstimePart;
                  dealstartdate = new Date(dealstartdate).getTime();
                }
                var currentdate=new Date();

                //Get Difference between Two dates
                var distance = enddate - (currentdate - offset_date);

                $('.sw-dailydeal-wrapper').show();

                if (distance < 0) {
                   // clearInterval(timer);
                    $('#expired_'+unique_id).html("<span style='font-size:25px; color:#000;'>EXPIRED!<span>");

                } else if(dealstartdate > currentdate) {
                   $('.countdowncontainer_'+unique_id).hide();
                   var msg="<span style='font-size:15px; color:#000;'> Coming Soon..<br>Deal Start at:<br>"+$('#'+startdateid).val()+"<span>";
                   $('#expired_'+unique_id).html(msg);
                } else {
                    var days = Math.floor(distance / _day);
                    var hours = Math.floor((distance % _day) / _hour);
                    var minutes = Math.floor((distance % _hour) / _minute);
                    var seconds = Math.floor((distance % _minute) / _second);

                    if(hours < 10)
                        hours = "0" + hours;
                    if(minutes < 10)
                        minutes = "0" + minutes;
                    if(seconds < 10)
                        seconds = "0" + seconds;
                    $('.countdowncontainer_'+unique_id).show();
                    $('#'+daysid).html(days);
                    $('#'+hoursid).html(hours);
                    $('#'+minutesid).html(minutes);
                    $('#'+secondsid).html(seconds);
                }
            });
        }

        // Set Interval
        timer = setInterval(function()
        {
            showRemaining();
        }, 1000);
    });
    </script>
<?php
    echo $block->getChildHtml('filter_toggle');
?>
